### ISSUE TITLE
deprecated division when using Dart Sass

### ISSUE THREAD

**Issue by r3plica** [crissdev/bootstrap-scss#11]
Hey, 
When building my project I get warnings stating that 

```
'sm': $grid-gutter / 6,
```

is deprecated and should be replaced with `math.div` or `calc`. Could this be done please?

**Comment by crissdev** [comment]
Hey @r3plica. This repository is only exposing (mirroring) the SCSS files from Bootstrap's project. You might consider posting this issue there instead. Thanks.
