### ISSUE TITLE
SCSS Error with numeric selectors on Grayscale

### ISSUE THREAD

**Issue by jdinartejesus** [crissdev/bootstrap-scss#14]
Hi,
Before anything, thanks for the library and for maintaining! 

I'm having an issue with the SCSS selector using numeric values, Eg: `.100{` since I'm moving our project to use `sass` module instead of `node-sass`. I know the issue would be solved by escaping the values (https://github.com/sass/sass/issues/2956, https://github.com/sass/sass/issues/255), but would be needed to add this to the core library.

Modules Versions:
```
bootstrap-scss: v4.6.1
sass-loader: v8.0.2
sass: v1.58.3
```

Variables creating the issue:
```
_variables.scss
$grays: map-merge(
  (
    "100": $gray-100,
    "200": $gray-200,
    ...
  ),
  $grays
);
```

Error message:
```
SassError: Expected identifier.
6 │   .100{
```

**Comment by crissdev** [comment]
This repository only mirrors the SCSS files from the Bootstrap project. It's not intended to be patched or have additional features.
