### ISSUE TITLE
classes like h-100 or w-100 are not found

### ISSUE THREAD

**Issue by bhaidar** [crissdev/bootstrap-scss#3]
Hi,
I am trying to use classes from Bootstrap like `h-100` and `w-100` but for some reason, they are not found.

Any idea how to fix that?

Thanks

**Comment by crissdev** [comment]
Hi @bhaidar . The library only exports the scss files from Bootstrap. No code removal is applied. Can you provide a live example (https://codepen.io/, https://jsfiddle.net/ etc)? Thanks

**Comment by bhaidar** [comment]
Hi @crissdev Thanks for getting back to me.
I've already added a custom prefix to some files and forgot about others! So `h-100` works but I was trying to access it with my own prefix. 

I fixed it now! Thanks :)
